name: Build and Test VSCode extension

on:
  push:
    branches: '**'
  pull_request:
    branches: [main]

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        runtime: [ linux, mac ]
     # Removing windows as a standard run flavor   runtime: [ linux, mac, windows ]
        targetVSCode: [previous, latest ]
      # As Vscode 1.79 and 1.78 are  the only support version for current release, running test with only latest,previous
      #Enable it in future for multiple releases as applicable  targetVSCode: [ previousMinusOne, previous, latest ]
        include:
        - runtime: linux
          os: ubuntu-latest

        - runtime: mac
          os: macOS-13

      #  - runtime: windows
      #    os: windows-latest

    name: Build Plugin
    runs-on: ${{ matrix.os }}

    steps:
      # Checkout the eclipse plugin repository.
      - name: 'Setup: Checkout plugin'
        uses: actions/checkout@v3

      # Install the required software.
      - name: 'Setup: Install required software'
        run: bash ./src/test/resources/ci/scripts/setup.sh

      # Build the plugin.
      - name: 'Build: Build-Package'
        run: bash ./src/test/resources/ci/scripts/exec.sh BUILD

      # Archive artifacts
      - name: Archive artifacts
        if: runner.os == 'linux' && matrix.targetVSCode == 'latest'
        uses: actions/upload-artifact@v3
        with:
          name: liberty-tools-vscode-${{ github.sha }}
          path: ./**/*.vsix
          if-no-files-found: warn
          retention-days: 7

      # Build the plugin.
      - name: 'Test: RunTests'
        run: bash ./src/test/resources/ci/scripts/exec.sh TEST ${{ matrix.targetVSCode }}

      # Archive screenshots
      - name: Archive screenshots
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: liberty-run-tests-screenshots-${{ runner.os }}-${{ matrix.targetVSCode }}
          path: ./screenshots/*.png
          if-no-files-found: warn
          retention-days: 7
